simple nueural network with 1 hidden layer solving mnist problem

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn import datasets
from sklearn import metrics
from sklearn import model_selection
from sklearn import preprocessing


In [2]:
#1. load minst data
digits = datasets.load_digits()
X = digits.data
y = digits.target

In [3]:
# 2. define model (ANN)
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(hidden_layer_sizes=(20,20,20), max_iter=1000)

In [4]:
# 3. split data
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.2)


In [5]:
# 4. train model
model.fit(X_train, y_train)

# 5. predict
y_pred = model.predict(X_test)

# 6. evaluate
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       0.90      0.96      0.93        28
           2       1.00      1.00      1.00        36
           3       1.00      0.95      0.98        42
           4       0.98      0.98      0.98        42
           5       0.95      1.00      0.97        37
           6       1.00      1.00      1.00        34
           7       0.95      0.95      0.95        38
           8       0.89      0.89      0.89        28
           9       0.95      0.90      0.92        39

    accuracy                           0.96       360
   macro avg       0.96      0.96      0.96       360
weighted avg       0.96      0.96      0.96       360

[[36  0  0  0  0  0  0  0  0  0]
 [ 0 27  0  0  0  0  0  0  1  0]
 [ 0  0 36  0  0  0  0  0  0  0]
 [ 0  0  0 40  0  0  0  0  1  1]
 [ 0  0  0  0 41  0  0  1  0  0]
 [ 0  0  0  0  0 37  0  0  0  0]
 [ 0  0  0  0  0  0 34  0  0  0]
 [ 0  1  0

OSError: [Errno 30] Read-only file system: 'model.pkl'